name: Parallel Jobs with Deployment

on:
  push:
    branches:
      - main
permissions: 
  contents: write
  id-token: write
  pages: write
  pull-requests: write
  deployments: write
  statuses: write
  checks: write
jobs:
  pg12:
    uses: ./.github/workflows/pg12.yml
  pg13:
    uses: ./.github/workflows/pg13.yml
  pg14:
    uses: ./.github/workflows/pg14.yml
  pg15:
    uses: ./.github/workflows/pg15.yml
  pg16:
    uses: ./.github/workflows/pg16.yml
  pg17:
    needs:
      - pg12
      - pg13
      - pg14
      - pg15
      - pg16
    uses: ./.github/workflows/pg17.yml