name: PostgreSQL Benchmark

on:
  workflow_call:
    inputs:
      pg_version:
        description: "PostgreSQL version to benchmark"
        required: true
        type: string

permissions:
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      PG_VERSION: ${{ inputs.pg_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PgBench
        run: |
          set -xe
          git pull
          # Remove existing PostgreSQL installation
          sudo apt-get remove --purge postgresql*
          sudo apt-get autoremove
          sudo rm -rf /var/lib/postgresql/
          sudo rm -rf /var/log/postgresql/
          sudo rm -rf /etc/postgresql/

          sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

          # Import the repository signing key:
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

          # Update the package lists:
          sudo apt-get update

          # Install PostgreSQL
          sudo apt-get install -y "postgresql-${{ inputs.pg_version }}"
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "CREATE USER test_user WITH PASSWORD 'test_password' CREATEDB;"

          # Get PostgreSQL full version
          PG_FULL_VERSION=$(sudo -u postgres psql -c "select version();" )
          if ! echo "$PG_FULL_VERSION" | grep -q "PostgreSQL ${{ env.PG_VERSION }}"; then
            echo "Error: Installed PostgreSQL version does not match requested version ${{ env.PG_VERSION }}"
            echo "Installed version: $PG_FULL_VERSION"
            exit 1
          fi
          # Create benchmark markdown file
          cat << EOF > hugosite/content/pg${PG_VERSION}.md
          +++
          date = '$(date +%Y-%m-%dT%H:%M:%S%z)'
          draft = false
          title = 'PostgreSQL ${{ env.PG_VERSION }} Benchmark Results'
          +++

          ## PgBench Results for PostgreSQL ${{ env.PG_VERSION }}

          ### PostgreSQL Version
          \`\`\`
          ${PG_FULL_VERSION}
          \`\`\`

          ### System Information
          \`\`\`
          $(lscpu | grep -E '^(Model name|CPU\(s\)|Thread|CPU MHz)')
          Memory: $(free -h | grep Mem | awk '{print $2}')
          \`\`\`

          EOF

          # Initialize and run benchmark
          sudo -u postgres pgbench -i 

          echo "### Benchmark Results" >> hugosite/content/pg${PG_VERSION}.md
          echo "\`\`\`" >> hugosite/content/pg${PG_VERSION}.md
          sudo -u postgres pgbench -n -c 16 -j 4 -T 60 -P 5 -U postgres postgres 2>&1 | tee >(cat >> hugosite/content/pg${PG_VERSION}.md)
          echo "\`\`\`" >> hugosite/content/pg${PG_VERSION}.md

      - name: Commit benchmark results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update PostgreSQL ${{ env.PG_VERSION }} benchmark results"
          file_pattern: "hugosite/content/pg${{ env.PG_VERSION }}.md"
          branch: main
          push_options: "--force-with-lease"
