name: PostgreSQL 14 Benchmark

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PostgreSQL 14
        uses: tj-actions/install-postgresql@v3
        with:
          postgresql-version: 14

      - name: Run PgBench
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "CREATE USER test_user WITH PASSWORD 'test_password' CREATEDB;"

          # Create benchmark markdown file
          cat << EOF > hugosite/content/benchmarkpg14.md
          +++
          date = '$(date +%Y-%m-%dT%H:%M:%S%z)'
          draft = false
          title = 'PostgreSQL 14 Benchmark Results'
          +++

          ## PgBench Results for PostgreSQL 14

          ### System Information
          \`\`\`
          $(lscpu | grep -E '^(Model name|CPU\(s\)|Thread|CPU MHz)')
          Memory: $(free -h | grep Mem | awk '{print $2}')
          \`\`\`

          EOF

          # Initialize and run benchmark
          sudo -u postgres pgbench -i 

          echo "### Benchmark Results" >> hugosite/content/benchmarkpg14.md
          echo "\`\`\`" >> hugosite/content/benchmarkpg14.md
          sudo -u postgres pgbench -c 16 -j 4 -T 60 -P 5 -U postgres postgres 2>&1 | tee >(cat >> hugosite/content/benchmarkpg14.md)
          echo "\`\`\`" >> hugosite/content/benchmarkpg14.md

      - name: Commit benchmark results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update PostgreSQL 14 benchmark results"
          file_pattern: 'hugosite/content/benchmarkpg14.md'