name: Prepare Mix Result
on:
  workflow_call:
permissions:
  contents: write
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Collect Mix Result
      run: |
        set -xe
        git pull
        chmod +x ./hugosite/collect-mix-result.sh
        ./hugosite/collect-mix-result.sh

    - name: Commit results
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update performance comparison chart"
        file_pattern: "hugosite/content/mix.md"
        branch: main
        push_options: "--force-with-lease"
