name: PostgreSQL Benchmark Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions: 
  contents: write
  id-token: write
  pages: write
  pull-requests: write
  deployments: write
  statuses: write
  checks: write
jobs:
  pg12:
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '12'
  pg13:
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '13'
  pg14:
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '14'
  pg15:
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '15'
  pg16:
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '16'
  pg17:
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '17'
  pg18:
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '18'
  prepareMixResult:
    needs: [pg12, pg13, pg14, pg15, pg16, pg17, pg18]
    uses: ./.github/workflows/prepare-mix-result.yml
  deploy:
    needs: prepareMixResult
    uses: ./.github/workflows/hugo.yml