name: PostgreSQL Benchmark Workflow

on:
  push:
    branches:
      - main
permissions: 
  contents: write
  id-token: write
  pages: write
  pull-requests: write
  deployments: write
  statuses: write
  checks: write
jobs:
  pg12:
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '12'
  pg13:
    needs: pg12
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '13'
  pg14:
    needs: pg13
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '14'
  pg15:
    needs: pg14
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '15'
  pg16:
    needs: pg15
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '16'
  pg17:
    needs: pg16
    uses: ./.github/workflows/pg-benchmark.yml
    with:
      pg_version: '17'
  prepareMixResult:
    needs: pg17
    uses: ./.github/workflows/prepare-mix-result.yml
  deploy:
    needs: prepareMixResult
    uses: ./.github/workflows/hugo.yml